### ISSUE TITLE
Not issue - question. Merge to DFs based on list of column names.

### ISSUE THREAD

**Issue by danduh** [data-forge/data-forge-js#1]
I'm wondering is there any way to merge two (or more) DFs based on multiple column names, similar to what pandas dataframe can do.

Thanks.

**Comment by ashleydavis** [comment]
Really sorry, only just saw this. Not sure why I didn't see it before now.

This feature has actually been added recently.

Please see the merge tests for examples: https://github.com/data-forge/data-forge-js/blob/master/test/merge-dataframe.test.js
