### ISSUE TITLE
Any chance on providing a types entry on DefinitelyTyped?

### ISSUE THREAD

**Issue by willkara** [data-forge/data-forge-js#10]
Not sure if this issue belongs here or on the data-forge-ts project.

https://github.com/DefinitelyTyped/DefinitelyTyped

I have this in my .ts file for my angular-cli project:

`import * as df from 'data-forge';

And WebStorm is giving me the error that it can't resolve the definitions for that module.

Funny thing is that I can still run the app no problem and it functions correctly.

**Comment by willkara** [comment]
Just as a side-note I tried

import * as df from 'data-forge-ts';

in my file and

    "data-forge-ts": "https://github.com/data-forge/data-forge-ts.git"


in packages.json and WebStorm is giving me a TON of errors where it 'cant find name/module' fs or requires.

**Comment by ashleydavis** [comment]
Thanks for logging an issue.

The TypeScript port of DataForge is in progress and not ready to be used yet. I'm doing a bit of work on it each day. It should be ready in 1 or 2 months. Until then you'll have to sit tight.

**Comment by willkara** [comment]
Of course, no rush at all :)

Awesome project so far.

I'd be happy to assist if you'd like.
