### ISSUE TITLE
Failed to minify in create-react-app

### ISSUE THREAD

**Issue by cuevash** [data-forge/data-forge-js#11]
Hi there,

When this module is added to a create-react-app in the process of building the application the next message is shown:

"
Failed to minify the code from this file: 

 	./node_modules/data-forge/src/series.js:2235 

Read more here: http://bit.ly/2tRViJ9
"
Basically it seems that the series.js contains es6 code when the create-react-app expects all the modules to be in es5 code .. 

Would it be possible to get a package build with full es5 support?

Thanks

**Comment by ashleydavis** [comment]
Hi I'm currently rebuilding DataForge with TypeScript, that means I'll be able to easily target ES5. 

Can you wait a few weeks?

The new repo is here, please check up on it and I'll announce in the readme when it's ready.

https://github.com/data-forge/data-forge-ts

I'll also be introducing the new version on my blog in the coming weeks:

http://www.the-data-wrangler.com/
