### ISSUE TITLE
Import into Angular 2 project.

### ISSUE THREAD

**Issue by compitDanielos** [data-forge/data-forge-js#4]
Hello,  I think it might be also actual to projects with React, Ionic, Typescript etc.

The error I'm getting:
```
ReferenceError: require is not defined(…) 
```

Simple solution is to create data-forje.bundle.js file that will contain all required('*') modules.

Thanks again for this great package.

**Comment by ashleydavis** [comment]
You can use the bower package for Ionic.

I'm using TypeScript now myself so I'd love to create type definitions for Data-Forge.
