### ISSUE TITLE
.average() returns NaN

### ISSUE THREAD

**Issue by vigsterkr** [data-forge/data-forge-js#5]
while both `max` and `min` works fine on the series, if i call `median` or `average` on the same series it returns `NaN`. i've tried `.where(v => isNaN(v)).count()`, but it returns 0, so this seems to be a real bug.

**Comment by ashleydavis** [comment]
What is your input data? Can you share it with me?

**Comment by ashleydavis** [comment]
Most Data-Forge function will return NaN if a bad value is input to them. The same is true of most JavaScript arithmetic functions. 

If you give me a code or input example I'll reopen this and look at it.
