### ISSUE TITLE
pivot API?

### ISSUE THREAD

**Issue by yiu31802** [data-forge/data-forge-js#7]
hello,

this is an invaluable dataframe library in javascript!

One thing I needed to self-implement was `Pivot` calculation, which simply counts the occurrence of records along interested two axis. See this example for more clarity, written for Apache Spark: https://databricks.com/blog/2016/02/09/reshaping-data-with-pivot-in-apache-spark.html

I managed to do the same thing in this `data-forge` but not using the built-in `pivot`. Looks like the built-in method is not designed for this purpose. I am willing to deliver a pull request but wanted to first confirm if my understanding is correct. And also a suggested name for a new API so that it does not conflict with an existing one.

Thanks,

Junji

**Comment by ashleydavis** [comment]
Thanks for logging an issue. 

I don't have time to look at this at the moment as I'm currently in the middle of porting [DataForge to TypeScript](https://github.com/data-forge/data-forge-ts).

It is something I would like to include so please feel free to have a go at it and I'll look at your pull request.

**Comment by ashleydavis** [comment]
Hi there,

I've updated the Data-Forge pivot function to work like Pandas. I'd love to get your feedback on it.

Please make sure you use the latest version of Data-Forge from npm.

Also please note that the repository has moved to here https://github.com/data-forge/data-forge-ts.
That's where you'll need to log new issues.

See here for examples of pivot: https://github.com/data-forge/data-forge-ts/blob/master/src/test/dataframe.pivot-example.test.ts

Examples where adapted from here: https://chrisalbon.com/python/data_wrangling/pandas_pivot_tables/
