### ISSUE TITLE
right value of join is null

### ISSUE THREAD

**Issue by blair-anson** [data-forge/data-forge-js#8]
Hi am having an issue with join() and joinOuterLeft()
I can run the join example here just fine...
https://www.npmjs.com/package/data-forge#join
However when I add my own data the join fails with an error that `right` is null
`TypeError: Cannot read property 'adjust' of null`

I suspect that I am missing something very obvious as opposed to is being a bug in your library, but the code appears identical to the example. Any help would be appreciated.

```
const dataB = [
    { "_id" : "5a651b801d6bd40443c98f38", "datetime" : new Date("2018-01-22T00:00:00Z"), "adjust" : 2 },
    { "_id" : "5a651b801d6bd40443c98f39", "datetime" : new Date("2018-01-23T00:00:00Z"), "adjust" : 2 },
    { "_id" : "5a651b801d6bd40443c98f40", "datetime" : new Date("2018-01-24T00:00:00Z"), "adjust" : 1 },
    { "_id" : "5a651b801d6bd40443c98f41", "datetime" : new Date("2018-01-25T00:00:00Z"), "adjust" : 1 }
];

const dataA = [
    {
        "datetime": new Date("2018-01-21T00:00:00.000Z"),
        "indexType": "stock",
        "vol": 5180900,
        "open": 7500,
        "high": 7579,
        "low": 7463,
        "close": 7579
    },
    {
        "datetime": new Date("2018-01-22T00:00:00.000Z"),
        "indexType": "stock",
        "vol": 6180900,
        "open": 7700,
        "high": 7706,
        "low": 7663,
        "close": 7679
    }
];

var df_a = new dataForge.DataFrame(dataA);
var df_b = new dataForge.DataFrame(dataB);

        var df_merged = df_a.joinOuterLeft(
            df_b,
            left => left.datetime,
            right => right.datetime,
            (left, right) => {
                return {
                    datetime: left.datetime,
                    vol: left.vol,
                    adjust: right.adjust
                };
            }
            )
        ;
```

**Comment by blair-anson** [comment]
I've narrowed the cause down the presence of date objects. Essentially if I try to join based on a series of date objects the join fails.

**Comment by ashleydavis** [comment]
Thanks for narrowing it down, I'm planning to have a look. Just trying to find the time.

**Comment by blair-anson** [comment]
Thanks, it might be because the equality comparison is looking for an exact
object match as opposed to the value of the object.

**Comment by ashleydavis** [comment]
Hey I think it's meant to work this way. 

From the api docs, joinOuterLeft 'Includes left elements that have no correlation'.

So, because the first item in `dataA` has no correlating item in `dataB`, the right value is set to null for it.

Are you sure you don't just want to use the `join `function?

**Comment by blair-anson** [comment]
> join() and joinOuterLeft()

As per my original comment I stated that it wasn't working for join() either.
Plus if you check the data in my examples there are some datetimes in dataA that are not in dataB, and vice-versa. So I should have seen something in the output, not just an empty array.

**Comment by ashleydavis** [comment]
Sorry I just ran your example code. I'll have a look tomorrow.

**Comment by ashleydavis** [comment]
I've tried your code with `join `instead of `joinOuterLeft `and it appears to work ok for me.

Your use of `joinOuterLeft `is as expected.

The problem doesn't seem to appear with the `join` function.

If you have another code sample you want me to look at please make sure it is complete, add it here and I'll reopen the issue.
